//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_AFS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public Kunde()
        {
            this.Sendungen = new HashSet<Sendung>();
            this.Ladestelle = new HashSet<Ladestelle>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adresse { get; set; }
        public string Hausnummer { get; set; }
        public short PLZ { get; set; }
        public string LKZ { get; set; }
    
        public virtual ICollection<Sendung> Sendungen { get; set; }
        public virtual ICollection<Ladestelle> Ladestelle { get; set; }
    }
}
