//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_AFS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ladestelle
    {
        public Ladestelle()
        {
            this.Kunde = new HashSet<Kunde>();
            this.Sendung = new HashSet<Sendung>();
            this.AnkommendeSendungen = new HashSet<Sendung>();
        }
    
        public int Id { get; set; }
        public string Adresse { get; set; }
        public short Hausnummer { get; set; }
        public short PLZ { get; set; }
        public string LKZ { get; set; }
    
        public virtual ICollection<Kunde> Kunde { get; set; }
        public virtual ICollection<Sendung> Sendung { get; set; }
        public virtual ICollection<Sendung> AnkommendeSendungen { get; set; }
    }
}
